'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------
Namespace WebFormsAIIntegration

    Public Partial Class HtmlEditor

        ''' <summary>
        ''' form1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected form1 As Global.System.Web.UI.HtmlControls.HtmlForm

        ''' <summary>
        ''' ASPxCallback1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected ASPxCallback1 As Global.DevExpress.Web.ASPxCallback

        ''' <summary>
        ''' ASPxHtmlEditor1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected ASPxHtmlEditor1 As Global.DevExpress.Web.ASPxHtmlEditor.ASPxHtmlEditor

        ''' <summary>
        ''' ASPxPopupControl1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected ASPxPopupControl1 As Global.DevExpress.Web.ASPxPopupControl

        ''' <summary>
        ''' AITextMemo control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected AITextMemo As Global.DevExpress.Web.ASPxMemo
    End Class
End Namespace
